/**
 * Auto-generated by scripts/updateFrontend.js on every deployment.
 *
 * Re-exports everything the frontend needs:
 *   - addresses.json  (per-network contract addresses)
 *   - abis/*          (full contract ABIs)
 *
 * Import example:
 *   import { getAddress, getAbi } from "../contracts";
 */

import addressesJson from "./addresses.json";
import BridgeTokenAbi from "./abis/BridgeToken.json";
import BridgeSepoliaAbi from "./abis/BridgeSepolia.json";
import BridgeAmoyAbi from "./abis/BridgeAmoy.json";

// ── Addresses ──────────────────────────────────────────────
// addresses.json shape: { "sepolia": { BridgeToken, BridgeSepolia }, "amoy": { BridgeToken, BridgeAmoy } }
const addresses = addressesJson;

/**
 * Look up a contract address for a given network + contract name.
 * @param {"sepolia"|"amoy"|"localhost"|"hardhat"} network
 * @param {"BridgeToken"|"BridgeSepolia"|"BridgeAmoy"} contractName
 */
export function getAddress(network, contractName) {
  return addresses[network]?.[contractName] || "";
}

export { addresses };

// ── ABIs ───────────────────────────────────────────────────
const abis = {
  BridgeToken: BridgeTokenAbi,
  BridgeSepolia: BridgeSepoliaAbi,
  BridgeAmoy: BridgeAmoyAbi,
};

export function getAbi(contractName) {
  return abis[contractName] || [];
}

export { BridgeTokenAbi, BridgeSepoliaAbi, BridgeAmoyAbi };
